# Conexión a una base de datos PostGresSql

In [1]:
import psycopg2
import pandas as pd

In [2]:
hosting = "dpg-d4ffs6gdl3ps73cu68t0-a.frankfurt-postgres.render.com"
puerto = "5432"
nombre_db = "the_bridge_school_db"
usuario = "agc79"
pswd = "un9XpRJkW4Dau1znXbLjzQxzSmNW2Lih"

In [3]:
def conexion(hosting, puerto, nombre_db, usuario, pswd):
        conn = psycopg2.connect(
                host = hosting,
                port = puerto,
                dbname = nombre_db,
                user = usuario,
                password = pswd
        )
        cursor = conn.cursor()
        return conn, cursor

"""
def sql_query(cursor, query):   # SELECT * FROM TRACKS

    # Ejecuta la query
    cursor.execute(query)

    # Almacena los datos de la query 
    ans = cursor.fetchall()

    # Obtenemos los nombres de las columnas de la tabla
    names = [description[0] for description in cursor.description]

    return pd.DataFrame(ans,columns=names)
"""

def sql_insert(cursor, conn,query):
    try:
        cursor.execute(query)
        conn.commit()
        return "OK"
    except Exception as e:
        return f"error: {e}"

In [4]:
conexion, cursor = conexion(hosting, puerto, nombre_db, usuario, pswd)

In [5]:
query_libro = "SELECT * FROM libro"
query_autor = "SELECT * FROM autor"
insert_autor = "INSERT INTO autor VALUES (3, 'Orwell', 'Britanico')"
insert_libro = "INSERT INTO libro VALUES (4, '1984', 3)"

"postgressql://USUARIO:CONTRASEÑA@HOST:PUERTO/NOMBRE_DB"

In [75]:
from sqlalchemy import create_engine

In [76]:
engine = create_engine("postgresql://agc79:un9XpRJkW4Dau1znXbLjzQxzSmNW2Lih@dpg-d4ffs6gdl3ps73cu68t0-a.frankfurt-postgres.render.com:5432/the_bridge_school_db")

In [77]:
df_alumnos_ds_01 = pd.read_csv(".\\data\\clase_1.csv", sep=";")
df_alumnos_ds_01

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment
0,Jafet Casals,Jafet_Casals@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
1,Jorge Manzanares,Jorge_Manzanares@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
2,Onofre Adadia,Onofre_Adadia@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,No Apto,Apto
3,Merche Prada,Merche_Prada@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,No Apto,Apto,No Apto
4,Pilar Abella,Pilar_Abella@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
5,Leoncio Tena,Leoncio_Tena@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
6,Odalys Torrijos,Odalys_Torrijos@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
7,Eduardo Caparrós,Eduardo_Caparrós@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
8,Ignacio Goicoechea,Ignacio_Goicoechea@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,No Apto,Apto
9,Clementina Santos,Clementina_Santos@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
10,Daniela Falcó,Daniela_Falcó@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
11,Abraham Vélez,Abraham_Vélez@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,No Apto,Apto,Apto
12,Maximiliano Menéndez,Maximiliano_Menéndez@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
13,Anita Heredia,Anita_Heredia@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
14,Eli Casas,Eli_Casas@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto

In [78]:
df_alumnos_ds_02 = pd.read_csv(".\\data\\clase_2.csv", sep=";")
df_alumnos_ds_02

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment
0,Guillermo Borrego,Guillermo_Borrego@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,No Apto,Apto,No Apto
1,Sergio Aguirre,Sergio_Aguirre@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,Apto,Apto,No Apto
2,Carlito Carrión,Carlito_Carrión@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,Apto,Apto,Apto
3,Haydée Figueroa,Haydée_Figueroa@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,Apto,Apto,Apto
4,Chita Mancebo,Chita_Mancebo@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,Apto,Apto
5,Joaquina Asensio,Joaquina_Asensio@gmail.com,Febrero,12/02/2024,Madrid,No Apto,No Apto,Apto,Apto,Apto
6,Cristian Sarabia,Cristian_Sarabia@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,No Apto,Apto,Apto
7,Isabel Ibáñez,Isabel_Ibáñez@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,Apto,Apto
8,Desiderio Jordá,Desiderio_Jordá@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,No Apto,Apto
9,Rosalina Llanos,Rosalina_Llanos@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,Apto,Apto,Apto

In [79]:
df_alumnos_ds_total = df_alumnos = pd.concat([df_alumnos_ds_01, df_alumnos_ds_02], ignore_index=True)
df_alumnos_ds_total

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment
0,Jafet Casals,Jafet_Casals@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
1,Jorge Manzanares,Jorge_Manzanares@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
2,Onofre Adadia,Onofre_Adadia@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,No Apto,Apto
3,Merche Prada,Merche_Prada@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,No Apto,Apto,No Apto
4,Pilar Abella,Pilar_Abella@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
5,Leoncio Tena,Leoncio_Tena@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
6,Odalys Torrijos,Odalys_Torrijos@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
7,Eduardo Caparrós,Eduardo_Caparrós@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
8,Ignacio Goicoechea,Ignacio_Goicoechea@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,No Apto,Apto
9,Clementina Santos,Clementina_Santos@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
10,Daniela Falcó,Daniela_Falcó@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
11,Abraham Vélez,Abraham_Vélez@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,No Apto,Apto,Apto
12,Maximiliano Menéndez,Maximiliano_Menéndez@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
13,Anita Heredia,Anita_Heredia@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
14,Eli Casas,Eli_Casas@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
15,Guillermo Borrego,Guillermo_Borrego@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,No Apto,Apto,No Apto
16,Sergio Aguirre,Sergio_Aguirre@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,Apto,Apto,No Apto
17,Carlito Carrión,Carlito_Carrión@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,Apto,Apto,Apto
18,Haydée Figueroa,Haydée_Figueroa@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,Apto,Apto,Apto
19,Chita Mancebo,Chita_Mancebo@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,Apto,Apto
20,Joaquina Asensio,Joaquina_Asensio@gmail.com,Febrero,12/02/2024,Madrid,No Apto,No Apto,Apto,Apto,Apto
21,Cristian Sarabia,Cristian_Sarabia@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,No Apto,Apto,Apto
22,Isabel Ibáñez,Isabel_Ibáñez@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,Apto,Apto
23,Desiderio Jordá,Desiderio_Jordá@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,No Apto,Apto
24,Rosalina Llanos,Rosalina_Llanos@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,Apto,Apto,Apto

In [83]:
# Convertir fecha a formato YYYY-MM-DD
df_alumnos_ds_total['Fecha_comienzo'] = pd.to_datetime(
    df_alumnos_ds_total['Fecha_comienzo'], 
    dayfirst=True
).dt.date

# Columnas de proyectos (solo para identificar bootcamp por proyecto)
proyectos_cols = ['Proyecto_HLF','Proyecto_EDA','Proyecto_BBDD','Proyecto_ML','Proyecto_Deployment']

# Pasar de ancho a largo
df_long = df_alumnos_ds_total.melt(
    id_vars=['Nombre','Email','Promoción','Fecha_comienzo','Campus'],
    value_vars=proyectos_cols,
    var_name='Proyecto',
    value_name='Calificacion'
)

# Bootcamp según proyecto (DS = 0)
bootcamp_map = {
    'Proyecto_HLF': 0,
    'Proyecto_EDA': 0,
    'Proyecto_BBDD': 0,
    'Proyecto_ML': 0,
    'Proyecto_Deployment': 0
}

# Promoción → ID
promocion_map = {
    'Febrero': 0,
    'Marzo': 1,
    'Abril': 2,
    'Junio': 3,
    'Septiembre': 4,
    'Octubre': 5
}

# Campus → ID
campus_map = {
    'Madrid': 0,
    'Valencia': 1,
    'Bilbao': 2,
    'Vitoria': 3,
    'Sevilla': 4
}

# Aplicar mapas
df_long['id_bootcamp'] = df_long['Proyecto'].map(bootcamp_map)
df_long['id_promocion'] = df_long['Promoción'].map(promocion_map)
df_long['id_campus'] = df_long['Campus'].map(campus_map)

# Crear id_alumno único empezando por 0
df_long['id_alumno'] = range(len(df_long))

# Seleccionar solo las columnas que existen en la tabla Alumno
df_final_alumnos_ds = df_long[
    ['id_alumno', 'Nombre', 'Email', 'id_bootcamp', 'id_promocion', 'id_campus', 'Fecha_comienzo']
]

# Renombrar columnas
df_final_alumnos_ds = df_final_alumnos_ds.rename(columns={
    'Nombre': 'nombre',
    'Email': 'email',
    'Fecha_comienzo': 'fecha_inicio'
})

df_final_alumnos_ds

,id_alumno,nombre,email,id_bootcamp,id_promocion,id_campus,fecha_inicio
0,0,Jafet Casals,Jafet_Casals@gmail.com,0,4,0,2023-09-18
1,1,Jorge Manzanares,Jorge_Manzanares@gmail.com,0,4,0,2023-09-18
2,2,Onofre Adadia,Onofre_Adadia@gmail.com,0,4,0,2023-09-18
3,3,Merche Prada,Merche_Prada@gmail.com,0,4,0,2023-09-18
4,4,Pilar Abella,Pilar_Abella@gmail.com,0,4,0,2023-09-18
...,...,...,...,...,...,...,...
120,120,Joaquina Asensio,Joaquina_Asensio@gmail.com,0,0,0,2024-02-12
121,121,Cristian Sarabia,Cristian_Sarabia@gmail.com,0,0,0,2024-02-12
122,122,Isabel Ibáñez,Isabel_Ibáñez@gmail.com,0,0,0,2024-02-12
123,123,Desiderio Jordá,Desiderio_Jordá@gmail.com,0,0,0,2024-02-12
124,124,Rosalina Llanos,Rosalina_Llanos@gmail.com,0,0,0,2024-02-12

In [85]:
df_final_alumnos_ds.to_sql("alumno", engine, if_exists="append", index= False)

125

In [67]:
df_alumnos_fs_01 = pd.read_csv(".\\data\\clase_3.csv", sep=";")
df_alumnos_fs_01

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullSatck
0,Amor Larrañaga,Amor_Larrañaga@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,No Apto
1,Teodoro Alberola,Teodoro_Alberola@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,No Apto,Apto,No Apto,Apto
2,Cleto Plana,Cleto_Plana@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,No Apto,Apto
3,Aitana Sebastián,Aitana_Sebastián@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,No Apto,Apto
4,Dolores Valbuena,Dolores_Valbuena@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,No Apto
5,Julie Ferrer,Julie_Ferrer@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,No Apto,No Apto,Apto,No Apto
6,Mireia Cabañas,Mireia_Cabañas@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
7,Flavia Amador,Flavia_Amador@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,No Apto,Apto,Apto
8,Albino Macias,Albino_Macias@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
9,Ester Sánchez,Ester_Sánchez@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,No Apto,Apto
10,Luis Miguel Galvez,Luis_Miguel_Galvez@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
11,Loida Arellano,Loida_Arellano@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
12,Heraclio Duque,Heraclio_Duque@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,No Apto,No Apto,No Apto
13,Herberto Figueras,Herberto_Figueras@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto

In [68]:
df_alumnos_fs_02 = pd.read_csv(".\\data\\clase_4.csv", sep=";")
df_alumnos_fs_02

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullSatck
0,Teresa Laguna,Teresa_Laguna@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
1,Estrella Murillo,Estrella_Murillo@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,Apto,Apto
2,Ernesto Uriarte,Ernesto_Uriarte@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
3,Daniela Guitart,Daniela_Guitart@gmail.com,Febrero,12/02/2024,Valencia,Apto,No Apto,No Apto,Apto,Apto
4,Timoteo Trillo,Timoteo_Trillo@gmail.com,Febrero,12/02/2024,Valencia,No Apto,Apto,Apto,Apto,No Apto
5,Ricarda Tovar,Ricarda_Tovar@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
6,Alejandra Vilaplana,Alejandra_Vilaplana@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,No Apto,Apto,Apto
7,Daniel Rosselló,Daniel_Rosselló@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,Apto,No Apto,No Apto
8,Rita Olivares,Rita_Olivares@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,No Apto,Apto,Apto
9,Cleto Montes,Cleto_Montes@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,Apto,Apto
10,Marino Castilla,Marino_Castilla@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,Apto,No Apto,No Apto
11,Estefanía Valcárcel,Estefanía_Valcárcel@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,No Apto,Apto
12,Noemí Vilanova,Noemí_Vilanova@gmail.com,Febrero,12/02/2024,Valencia,Apto,No Apto,No Apto,Apto,Apto

In [69]:
df_alumnos_fs_total = df_alumnos = pd.concat([df_alumnos_fs_01, df_alumnos_fs_02], ignore_index=True)
df_alumnos_fs_total

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullSatck
0,Amor Larrañaga,Amor_Larrañaga@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,No Apto
1,Teodoro Alberola,Teodoro_Alberola@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,No Apto,Apto,No Apto,Apto
2,Cleto Plana,Cleto_Plana@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,No Apto,Apto
3,Aitana Sebastián,Aitana_Sebastián@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,No Apto,Apto
4,Dolores Valbuena,Dolores_Valbuena@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,No Apto
5,Julie Ferrer,Julie_Ferrer@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,No Apto,No Apto,Apto,No Apto
6,Mireia Cabañas,Mireia_Cabañas@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
7,Flavia Amador,Flavia_Amador@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,No Apto,Apto,Apto
8,Albino Macias,Albino_Macias@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
9,Ester Sánchez,Ester_Sánchez@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,No Apto,Apto
10,Luis Miguel Galvez,Luis_Miguel_Galvez@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
11,Loida Arellano,Loida_Arellano@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
12,Heraclio Duque,Heraclio_Duque@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,No Apto,No Apto,No Apto
13,Herberto Figueras,Herberto_Figueras@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
14,Teresa Laguna,Teresa_Laguna@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
15,Estrella Murillo,Estrella_Murillo@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,Apto,Apto
16,Ernesto Uriarte,Ernesto_Uriarte@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
17,Daniela Guitart,Daniela_Guitart@gmail.com,Febrero,12/02/2024,Valencia,Apto,No Apto,No Apto,Apto,Apto
18,Timoteo Trillo,Timoteo_Trillo@gmail.com,Febrero,12/02/2024,Valencia,No Apto,Apto,Apto,Apto,No Apto
19,Ricarda Tovar,Ricarda_Tovar@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
20,Alejandra Vilaplana,Alejandra_Vilaplana@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,No Apto,Apto,Apto
21,Daniel Rosselló,Daniel_Rosselló@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,Apto,No Apto,No Apto
22,Rita Olivares,Rita_Olivares@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,No Apto,Apto,Apto
23,Cleto Montes,Cleto_Montes@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,Apto,Apto
24,Marino Castilla,Marino_Castilla@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,Apto,No Apto,No Apto
25,Estefanía Valcárcel,Estefanía_Valcárcel@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,No Apto,Apto
26,Noemí Vilanova,Noemí_Vilanova@gmail.com,Febrero,12/02/2024,Valencia,Apto,No Apto,No Apto,Apto,Apto

In [ ]:
# Convertir fecha a formato YYYY-MM-DD
df_alumnos_fs_total['Fecha_comienzo'] = pd.to_datetime(
    df_alumnos_fs_total['Fecha_comienzo'],
    dayfirst=True
).dt.date

# Columnas de proyectos (solo para identificar bootcamp por proyecto)
proyectos_cols_fs = [
    'Proyecto_WebDev',
    'Proyecto_FrontEnd',
    'Proyecto_Backend',
    'Proyecto_React',
    'Proyecto_FullSatck'
]

# Pasar de ancho a largo
df_long_fs = df_alumnos_fs_total.melt(
    id_vars=['Nombre','Email','Promoción','Fecha_comienzo','Campus'],
    value_vars=proyectos_cols_fs,
    var_name='Proyecto',
    value_name='Calificacion'
)

# Bootcamp según proyecto (FS = 1)
bootcamp_map_fs = {p: 1 for p in proyectos_cols_fs}

# Promoción → ID
promocion_map = {
    'Febrero': 0,
    'Marzo': 1,
    'Abril': 2,
    'Junio': 3,
    'Septiembre': 4,
    'Octubre': 5
}

# Campus → ID
campus_map = {
    'Madrid': 0,
    'Valencia': 1,
    'Bilbao': 2,
    'Vitoria': 3,
    'Sevilla': 4
}

# Aplicar mapas
df_long_fs['id_bootcamp'] = df_long_fs['Proyecto'].map(bootcamp_map_fs)
df_long_fs['id_promocion'] = df_long_fs['Promoción'].map(promocion_map)
df_long_fs['id_campus'] = df_long_fs['Campus'].map(campus_map)

# Crear id_alumno único empezando justo después de DS
start_id = df_final_alumnos_ds['id_alumno'].max() + 1
df_long_fs['id_alumno'] = range(start_id, start_id + len(df_long_fs))

# Seleccionar solo las columnas que existen en la tabla Alumno (SIN id_proyecto)
df_final_alumnos_fs = df_long_fs[
    ['id_alumno', 'Nombre', 'Email', 'id_bootcamp', 'id_promocion', 'id_campus', 'Fecha_comienzo']
]

# Renombrar columnas
df_final_alumnos_fs = df_final_alumnos_fs.rename(columns={
    'Nombre': 'nombre',
    'Email': 'email',
    'Fecha_comienzo': 'fecha_inicio'
})

df_final_alumnos_fs

,id_alumno,nombre,email,id_bootcamp,id_promocion,id_campus,fecha_inicio
0,125,Amor Larrañaga,Amor_Larrañaga@gmail.com,1,4,0,2023-09-18
1,126,Teodoro Alberola,Teodoro_Alberola@gmail.com,1,4,0,2023-09-18
2,127,Cleto Plana,Cleto_Plana@gmail.com,1,4,0,2023-09-18
3,128,Aitana Sebastián,Aitana_Sebastián@gmail.com,1,4,0,2023-09-18
4,129,Dolores Valbuena,Dolores_Valbuena@gmail.com,1,4,0,2023-09-18
...,...,...,...,...,...,...,...
130,255,Rita Olivares,Rita_Olivares@gmail.com,1,0,1,2024-02-12
131,256,Cleto Montes,Cleto_Montes@gmail.com,1,0,1,2024-02-12
132,257,Marino Castilla,Marino_Castilla@gmail.com,1,0,1,2024-02-12
133,258,Estefanía Valcárcel,Estefanía_Valcárcel@gmail.com,1,0,1,2024-02-12
134,259,Noemí Vilanova,Noemí_Vilanova@gmail.com,1,0,1,2024-02-12

In [93]:
# Insertar en la tabla
df_final_alumnos_fs.to_sql("alumno", engine, if_exists="append", index=False)

135

In [ ]:
df_proy_ds = df_long[['Calificacion']].copy()  
df_proy_ds['id_alumno'] = df_final_alumnos_ds['id_alumno'].values
df_proy_ds['id_bootcamp'] = 0  # Bootcamp DS

df_proy_ds['Calificacion'] = pd.to_numeric(df_proy_ds['Calificacion'], errors='coerce')
df_proy_ds['calificacion'] = df_proy_ds['Calificacion'].apply(
    lambda x: 'apto' if x >= 5 else 'no apto'
)

df_proy_fs = df_long_fs[['Calificacion']].copy()  # df_long_fs es FS
df_proy_fs['id_alumno'] = df_final_alumnos_fs['id_alumno'].values
df_proy_fs['id_bootcamp'] = 1  # Bootcamp FS

df_proy_fs['Calificacion'] = pd.to_numeric(df_proy_fs['Calificacion'], errors='coerce')
df_proy_fs['calificacion'] = df_proy_fs['Calificacion'].apply(
    lambda x: 'apto' if x >= 5 else 'no apto'
)

df_proyectos_realizados = pd.concat([df_proy_ds, df_proy_fs], ignore_index=True)

df_proyectos_realizados['id_proyectos_realizados'] = range(len(df_proyectos_realizados))

df_proyectos_realizados = df_proyectos_realizados[
    ['id_proyectos_realizados', 'id_alumno', 'id_bootcamp', 'calificacion']
]

In [ ]:
df_proyectos_realizados.to_sql("proyectos_realizados", engine, if_exists="append", index=False)

260

In [11]:
df_profesores = pd.read_csv(".\\data\\claustro.csv", sep=";")
df_profesores

               Nombre Rol Vertical   Promocion    Campus   Modalidad
0           Noa Yáñez  TA       DS  Septiembre    Madrid  Presencial
1   Saturnina Benitez  TA       DS  Septiembre    Madrid  Presencial
2          Anna Feliu  TA       FS  Septiembre    Madrid  Presencial
3       Rosalva Ayuso  TA       FS  Septiembre  Valencia  Presencial
4    Ana Sofía Ferrer  TA       FS     Febrero  Valencia  Presencial
5     Angélica Corral  TA       FS     Febrero    Madrid  Presencial
6         Ariel Lledó  TA       DS  Septiembre    Madrid  Presencial
7         Mario Prats  LI       FS     Febrero  Valencia      Online
8   Luis Ángel Suárez  LI       FS  Septiembre    Madrid      Online
9  María Dolores Diaz  LI       DS  Septiembre    Madrid      Online

In [18]:
df_bootcamp = pd.DataFrame({"id_bootcamp": [0, 1],"nombre": ["Data Science", "Full Stack"]})
df_bootcamp

   id_bootcamp        nombre
0            0  Data Science
1            1    Full Stack